<?php

namespace Database\Seeders;

use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillUserSeeder extends Seeder
{
    public $user_skills = [
        [ 'user_id' =>1,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'SPA' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'MVC' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>1,  'skill_name' => 'NuxtJS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>1,  'skill_name' => 'Vue.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'Jquery' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>1,  'skill_name' => 'PHP' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>1,  'skill_name' => 'Laravel' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4.5],
        [ 'user_id' =>1,  'skill_name' => 'MySQL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>1,  'skill_name' => 'Ruby' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>1,  'skill_name' => 'Ruby on Rails' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>1],
        [ 'user_id' =>1,  'skill_name' => 'C#' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>2,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'SPA' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'DDD' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>2,  'skill_name' => 'NuxtJS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4],
        [ 'user_id' =>2,  'skill_name' => 'Next.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>2,  'skill_name' => 'Jquery' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'PHP' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4.5],
        [ 'user_id' =>2,  'skill_name' => 'Laravel' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4],
        [ 'user_id' =>2,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'PG' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'Ruby' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'Ruby on Rails' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>2,  'skill_name' => 'go' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>2,  'skill_name' => 'Beego' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>3,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'MVC' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'Repository' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>3,  'skill_name' => 'Next.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>3,  'skill_name' => 'Vue.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'Jquery' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'Ruby' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4.5],
        [ 'user_id' =>3,  'skill_name' => 'Ruby on Rails' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3.5],
        [ 'user_id' =>3,  'skill_name' => 'PHP' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4],
        [ 'user_id' =>3,  'skill_name' => 'Laravel' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3.5],
        [ 'user_id' =>3,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'vercel' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'SSR' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>3,  'skill_name' => 'Typescript' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>3,  'skill_name' => 'Node.js' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>3,  'skill_name' => 'Express.js' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>1],
        [ 'user_id' =>4,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'SSR' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'TDD' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>4,  'skill_name' => 'Next.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>4,  'skill_name' => 'PHP' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4],
        [ 'user_id' =>4,  'skill_name' => 'Laravel' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'MySQL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'PG' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'PO' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'PMO' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => '単体試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => '保守' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>4,  'skill_name' => 'go' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>4,  'skill_name' => 'echo' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>1],
        [ 'user_id' =>4,  'skill_name' => 'C#' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>1],
        [ 'user_id' =>5,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'SSR' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'MVC' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'Ruby' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>5,  'skill_name' => 'Ruby on Rails' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4.5],
        [ 'user_id' =>5,  'skill_name' => 'go' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>5,  'skill_name' => 'beego' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4.5],
        [ 'user_id' =>5,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3.5],
        [ 'user_id' =>5,  'skill_name' => 'Vue.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'GCP' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'MongoDB' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'vercel' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => '単体試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => '保守' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>5,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'SPA' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'MVC' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'TDD' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'SSR' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'DDD' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'Repository' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>6,  'skill_name' => 'NuxtJS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>6,  'skill_name' => 'Vue.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'Jquery' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>6,  'skill_name' => 'HTML' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>6,  'skill_name' => 'CSS' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>6,  'skill_name' => 'SCSS' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>6,  'skill_name' => 'MariaDB' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => 'SE' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => '単体試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>6,  'skill_name' => '保守' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'SPA' ,  'is_practice' =>2,  'is_learning' =>2, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3.5],
        [ 'user_id' =>7,  'skill_name' => 'Vue.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'Next.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'go' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>7,  'skill_name' => 'Beego' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>7,  'skill_name' => 'Echo' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4.5],
        [ 'user_id' =>7,  'skill_name' => 'MySQL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'Typescript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4],
        [ 'user_id' =>7,  'skill_name' => 'NuxtJS' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>7,  'skill_name' => 'MVC' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>7,  'skill_name' => 'C#' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>7,  'skill_name' => 'ASP.NET Core MVC' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>0.5],
        [ 'user_id' =>8,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'SPA' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'MVC' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'DDD' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'Repository' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'Typescript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>8,  'skill_name' => 'Next.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3.5],
        [ 'user_id' =>8,  'skill_name' => 'C#' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>8,  'skill_name' => 'ASP.NET Core MVC' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>8,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'PG' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'Java' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'Spring Boot' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>2],
        [ 'user_id' =>8,  'skill_name' => 'Node.js' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>8,  'skill_name' => 'Express.js' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>1],
        [ 'user_id' =>8,  'skill_name' => 'PHP' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>0.5],
        [ 'user_id' =>9,  'skill_name' => 'ウォーターフォール' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'SSR' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'DDD' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4],
        [ 'user_id' =>9,  'skill_name' => 'Jquery' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3.5],
        [ 'user_id' =>9,  'skill_name' => 'Java' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>9,  'skill_name' => 'Spring Boot' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>9,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'MongoDB' ,  'is_practice' =>0,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'PostgreSQL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'Azure' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'PG' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'PO' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => 'PMO' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => '単体試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>9,  'skill_name' => '保守' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'アジャイル（スクラム）' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'SSR' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'TDD' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'Javascript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>10,  'skill_name' => 'Typescript' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4.5],
        [ 'user_id' =>10,  'skill_name' => 'Next.js' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>10,  'skill_name' => 'PHP' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>10,  'skill_name' => 'laravel' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>4],
        [ 'user_id' =>10,  'skill_name' => 'C#' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>10,  'skill_name' => 'ASP.NET Core MVC' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>5],
        [ 'user_id' =>10,  'skill_name' => 'MariaDB' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'AWS' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'PM' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'PL' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'SE' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'PG' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'PO' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => 'PMO' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => '要件設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => '基本設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => '詳細設計' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => '製造' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => '結合・総合試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => '単体試験' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
        [ 'user_id' =>10,  'skill_name' => '保守' ,  'is_practice' =>1,  'is_learning' =>1, 'level' =>3],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->user_skills as $user_skill) {
            $skill = Skill::firstWhere('name', $user_skill['skill_name']);
            if ($skill == NULL) continue;

            DB::table('skill_user')->insert(
                [
                    'user_id' => $user_skill['user_id'],
                    'skill_id' => $skill->id,
                    'is_practice' => $user_skill['is_practice'],
                    'is_learning' => $user_skill['is_learning'],
                    'level' => $user_skill['level'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
